# Generated by Django 5.2.5 on 2026-08-14 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=50)),
                ("numeric_price", models.FloatField(default=0.0)),
                ("category", models.CharField(default="popular", max_length=100)),
                (
                    "sub_category",
                    models.CharField(default="traditional", max_length=100),
                ),
                ("img", models.CharField(default="/assets/b1.avif", max_length=255)),
                ("url", models.CharField(blank=True, default="", max_length=255)),
                ("tag", models.CharField(blank=True, default="", max_length=100)),
                (
                    "tag_color",
                    models.CharField(blank=True, default="orange", max_length=50),
                ),
                (
                    "tape_color",
                    models.CharField(blank=True, default="orange", max_length=50),
                ),
                ("rating", models.CharField(default="4.9", max_length=20)),
                ("reviews", models.IntegerField(default=100)),
                ("perk", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("total_amount", models.CharField(max_length=50)),
                ("numeric_total", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Delivered", "Delivered"),
                            ("In Transit 🚚", "In Transit 🚚"),
                            ("Processing 📦", "Processing 📦"),
                            ("Confirmed ✅", "Confirmed ✅"),
                        ],
                        default="Confirmed ✅",
                        max_length=50,
                    ),
                ),
                ("shipping_name", models.CharField(max_length=150)),
                ("shipping_phone", models.CharField(max_length=50)),
                ("shipping_address", models.TextField()),
                ("shipping_city", models.CharField(max_length=100)),
                ("shipping_pincode", models.CharField(max_length=20)),
                ("payment_method", models.CharField(default="upi", max_length=50)),
                ("points_earned", models.IntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=50)),
                ("numeric_price", models.FloatField(default=0.0)),
                ("quantity", models.IntegerField(default=1)),
                ("img", models.CharField(blank=True, default="", max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=150)),
                ("points", models.IntegerField(default=50)),
                ("tier", models.CharField(default="Junior Maker 🌱", max_length=100)),
                ("avatar", models.CharField(default="/assets/4.png", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=50)),
                ("numeric_price", models.FloatField(default=0.0)),
                ("img", models.CharField(blank=True, default="", max_length=255)),
                ("url", models.CharField(blank=True, default="", max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "product_id")},
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("price", models.CharField(blank=True, default="", max_length=50)),
                ("img", models.CharField(blank=True, default="", max_length=255)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "product_id")},
            },
        ),
    ]
