# Generated by Django 5.2.5 on 2026-08-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_passwordresetcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
